"""
Minimal stub for playwright.async_api so that Pyre2 can resolve the import.
The real playwright package is installed in site-packages and used at runtime.
"""
from typing import Any, Callable, Optional


class TimeoutError(Exception):
    """Playwright-style timeout error."""
    pass


class Locator:
    first: "Locator"

    async def click(self, timeout: int = 30000) -> None: ...
    async def clear(self) -> None: ...
    async def type(self, text: str, delay: int = 0) -> None: ...
    async def fill(self, value: str) -> None: ...
    def first(self) -> "Locator": ...


class Page:
    @property
    def url(self) -> str: ...

    async def goto(self, url: str, wait_until: str = "load", timeout: int = 30000) -> None: ...
    async def click(self, selector: str, timeout: int = 30000) -> None: ...
    async def inner_text(self, selector: str) -> str: ...
    async def close(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def locator(self, selector: str) -> Locator: ...
    def get_by_text(self, text: str, exact: bool = True) -> Locator: ...
    def get_by_role(self, role: str) -> Locator: ...
    def get_by_placeholder(self, placeholder: str, exact: bool = True) -> Locator: ...
    def get_by_label(self, label: str, exact: bool = True) -> Locator: ...

    class mouse:
        @staticmethod
        async def wheel(x: float, y: float) -> None: ...

    class keyboard:
        @staticmethod
        async def press(key: str) -> None: ...


class BrowserContext:
    async def new_page(self) -> Page: ...
    async def close(self) -> None: ...


class Browser:
    def is_connected(self) -> bool: ...
    async def new_context(self, viewport: Any = None, user_agent: str = "") -> BrowserContext: ...
    async def close(self) -> None: ...


class BrowserType:
    async def launch(self, **kwargs: Any) -> Browser: ...
    async def connect_over_cdp(self, endpoint_url: str) -> Browser: ...


class Playwright:
    chromium: BrowserType
    firefox: BrowserType
    webkit: BrowserType
    async def stop(self) -> None: ...


class AsyncPlaywrightContextManager:
    async def start(self) -> Playwright: ...
    async def __aenter__(self) -> Playwright: ...
    async def __aexit__(self, *args: Any) -> None: ...


def async_playwright() -> AsyncPlaywrightContextManager: ...
